name: application_hydrogami
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  gap: ^3.0.1
  carousel_slider: ^4.2.0
  google_fonts: ^4.0.4
  intl: ^0.19.0
  salomon_bottom_bar: ^3.3.2
  http: ^0.13.4
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
